[dependencies]
base = "0.11.1"
mospec = "https://github.com/MoSpec/mo-spec#v0.1.0@e962a9cb73d9886b7bb6525e2396c5af1c6a2102"
canistergeek = "https://github.com/usergeek/canistergeek-ic-motoko#master@32d1f3a48b1bc12d727b896a69b08bb5f3e5860d"

[dev-dependencies]
test = "1.2.0"