[dependencies]
base = "0.12.1"
canistergeek = "https://github.com/usergeek/canistergeek-ic-motoko#master@32d1f3a48b1bc12d727b896a69b08bb5f3e5860d"
map = "9.0.1"
fuzz = "0.2.1"

[dev-dependencies]
test = "2.0.0"