name: "test"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm config set //npm.pkg.github.com/:_authToken ${{ secrets.WORKFLOW_PERSONAL_TOKEN }}
      - run: npm clean-install
      - name: "check prettier"
        run: npm run prettier:check
      - name: "audit"
        run: npm audit
      - name: "install dfx"
        # download and setup local moc by starting dfx once
        run: |
          sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
          dfx start --background
          dfx stop
      - name: "install mops packages"
        run: |
          npm i -g ic-mops
          mops install
      - name: "run tests"
        run: npm test
